### ISSUE TITLE
Error importing dependency-check report

### ISSUE THREAD

**Issue by RenePingen** [stevespringett/dependency-check-sonar-plugin#49]
In the newer version of the dependency scanner a ? can be included in the file path of issues. This ? is causing the import to fail. Quick fix would be to filter out the ? part of the path.

Caused by: java.nio.file.InvalidPathException: Illegal char <?> at index 39: ..\package.json?moment
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.io.File.toPath(Unknown Source)
        at org.sonar.api.scan.filesystem.PathResolver.relativePath(PathResolver.java:121)
        at org.sonar.api.batch.fs.internal.AbsolutePathPredicate.get(AbsolutePathPredicate.java:52)
        at org.sonar.api.batch.fs.internal.DefaultFileSystem.inputFiles(DefaultFileSystem.java:149)
        at org.sonar.api.batch.fs.internal.DefaultFileSystem.inputFile(DefaultFileSystem.java:115)
        at org.sonar.dependencycheck.DependencyCheckSensor.addIssues(DependencyCheckSensor.java:126)
        at org.sonar.dependencycheck.DependencyCheckSensor.execute(DependencyCheckSensor.java:209)
        ... 35 more

**Comment by stevespringett** [comment]
The SonarQube plugin does not scan. It requires the XML output from a Dependency-Check implementation (CLI, Maven, Jenkins, etc). In the SQ configuration, you specify the path to the XML file. Refer to the readme and examples.

**Comment by RenePingen** [comment]
HI steve,

Maybe I phrased the issue a bit unclear. I am aware of how the plugin works. the **latest** version of the owasp command line scanner on nodejs project returns an xml file which contains the following code:
"
        <dependency isVirtual="false">
            <fileName>moment:2.11.2</fileName>
            <filePath>C:\agent\_work\14\s\server\package.json?moment</filePath>
"
The filepath part of the XML contains a '?' character, which causes the sonarqube import plugin to fail with the stacktrace as pointed above.

Btw i managed to workaround the issue by reverting to an older version of the OWASP dependency scanner command line tool.
Nonetheless, I think it should be relatively easy to fix.

Kind regards,

René

**Comment by stevespringett** [comment]
Ah, thanks for the clarification.

**Comment by stevespringett** [comment]
The issue should be resolved now.
